language: swift
osx_image: xcode11.1
xcode_project: BookPlayer.xcodeproj
xcode_scheme: BookPlayer
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 8
cache:
  directories:
  - Carthage
  - $HOME/Library/Caches/Homebrew
before_script:
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds
  - swiftlint
