language: swift
osx_image: xcode10
cache:
  directories:
  - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
install:
  - bundle install
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
script:
  - fastlane tests
